### ISSUE TITLE
Icon doesnt change 

### ISSUE THREAD

**Issue by JaneJaneJayne** [Shaneee/AuthenticWeather-Rainmeter#1]
Hi there, I noticed that "ImageName=#IconPath#default.png" in AuthenticWeather.ini, is the reason why the icon doesnt change according to the API call. I would love to know how to make it work, since i'm new to rainmeter.

Great work btw :)

**Comment by Shaneee** [comment]
Fix here, https://github.com/Shaneee/AuthenticWeather-Rainmeter/commit/2f1281ac06f7f64d6940d61ab43c04b5d39c9ccf
